### ISSUE TITLE
¿Preprocesadores, cuál y por qué?

### ISSUE THREAD

**Issue by ValKiriann** [Frontaneria/Open-Support#6]
Hola!

Todavía no he aprendido ningún preprocesador y a la hora de hacerlo me gustaría saber cuál es el que vosotros habeis elegido y por qué. En principio pienso que Sass es el que debería aprender pero no estoy segura. 

Gracias de antemano

**Comment by Angelmmiguel** [comment]
Hola @ValKiriann,

La gran ventaja del uso de preprocesadores es que te **permiten ampliar las funcionalidades del lenguaje CSS sin que esto afecte al usuario final**. El usuario final siempre recibirá un fichero CSS válido por lo que no hay que lidiar con la compatibilidad de las características de CSS en los navegadores. Algunas funcionalidades a destacar son:

* Variables (Aunque actualmente ya tenemos las [CSS Custom Properties](http://caniuse.com/#feat=css-variables)
* Funciones
* Arrays y maps (hash)
* Iteradores
* ...

Dentro del ecosistema CSS, cabe destacar tres preprocesadores:

* [Less](http://lesscss.org/)
* [Stylus](http://stylus-lang.com/)
* [SASS](http://sass-lang.com/)

En mi caso, **utilizo SASS** en mis proyectos. Concretamente, la sintaxis definida en la versión 3: **SCSS**. Estos tres preprocesadores disponen de todas las funcionalidades más destacadas. Mirando la documentación no encuentro ninguna funcionalidad que eche en falta ninguno de ellos.

Mi decisión de utilizar SCSS va más orientada por la sintaxis del código. Vamos a poner de ejemplo la definición de una función y el uso en un selector para los tres preprocesadores:

**Less**
```less
.left-border-radius (@radius) {
  border-radius: @radius 0 0 @radius;
}

.left-button {
  .left-border-radius(10px);
}
```
**Stylus**
```styl
left-border-radius()
  border-radius: arguments 0 0 arguments

// Los paréntesis son opcionales, al igual que el ;
.left-button {
  left-border-radius: 10px;
}
``` 
**SCSS**
```scss
@mixin left-border-radius($radius) {
  border-radius: $radius 0 0 $radius;
}

.left-button {
  @include left-border-radius(10px);
}
``` 

El resultado CSS es el mismo para los tres casos:

```css
.left-button {
  border-radius: 10px 0 0 10px;
}
```

No obstante, la sintaxis es completamente diferente. En el caso de Less, la defición de una función es muy similar a la de una clase de CSS. El uso del `.` como elemento para definir y usar una función me parece muy confuso ya que es un símbolo fundamental de CSS.

El caso de stylus es parecido. La llamada a funciones es igual que la declaración de propiedades. Para alguien que llega al proyecto y no conoce la sintaxis de Stylus, esta le puede llevar a pensar que la declaración tiene un error tipográfico. Además, si se redefine una propiedad de CSS, lo cual es posible, el resultado puede ser un auténtico caos.

En cambio, la sintaxis de SCSS especifica de manera muy clara qué es CSS y qué es código SCSS. Además, la sintaxis es muy similar al resultado CSS (obviando la definición de la función), por lo que la curva de aprendizaje es más baja. Todo ello sin perder ventajas de otros preprocesadores.

Espero que esta respuesta te sirva de ayuda. 

Bienvenida a Open Support :)
